CREATE TABLE accessory
(
    id   BIGINT       NOT NULL,
    type VARCHAR(255) NOT NULL,
    CONSTRAINT pk_accessory PRIMARY KEY (id)
);

CREATE TABLE addresses
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    street           VARCHAR(255),
    house_number     VARCHAR(255),
    apartment_number VARCHAR(255),
    postal_code      VARCHAR(255),
    city             VARCHAR(255),
    type             VARCHAR(255),
    user_id          BIGINT,
    CONSTRAINT pk_addresses PRIMARY KEY (id)
);

CREATE TABLE cart_item
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT,
    product_id BIGINT                                  NOT NULL,
    quantity   INTEGER                                 NOT NULL,
    session_id VARCHAR(255),
    CONSTRAINT pk_cart_item PRIMARY KEY (id)
);

CREATE TABLE image
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url        VARCHAR(255),
    product_id BIGINT,
    public_id  VARCHAR(255),
    CONSTRAINT pk_image PRIMARY KEY (id)
);

CREATE TABLE order_item
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id          BIGINT                                  NOT NULL,
    product_id        BIGINT                                  NOT NULL,
    quantity          INTEGER                                 NOT NULL,
    price_at_purchase DECIMAL                                 NOT NULL,
    CONSTRAINT pk_order_item PRIMARY KEY (id)
);

CREATE TABLE orders
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id             BIGINT,
    status              VARCHAR(255)                            NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    email               VARCHAR(255),
    phone_number        VARCHAR(255),
    guest_name          VARCHAR(255),
    shipping_address_id BIGINT,
    session_id          VARCHAR(255),
    paid_at             TIMESTAMP WITHOUT TIME ZONE,
    is_paid             BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    price       DECIMAL(10, 2)                          NOT NULL,
    description TEXT,
    stock       INTEGER                                 NOT NULL,
    type        VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

CREATE TABLE rim
(
    id           BIGINT       NOT NULL,
    material     VARCHAR(255) NOT NULL,
    size         VARCHAR(255) NOT NULL,
    bolt_pattern VARCHAR(255) NOT NULL,
    CONSTRAINT pk_rim PRIMARY KEY (id)
);

CREATE TABLE roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE shipping_address
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    street           VARCHAR(255)                            NOT NULL,
    house_number     VARCHAR(255)                            NOT NULL,
    apartment_number VARCHAR(255),
    postal_code      VARCHAR(255)                            NOT NULL,
    city             VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_shipping_address PRIMARY KEY (id)
);

CREATE TABLE tire
(
    id     BIGINT       NOT NULL,
    season VARCHAR(255) NOT NULL,
    size   VARCHAR(255) NOT NULL,
    CONSTRAINT pk_tire PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id)
);

CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username     VARCHAR(100)                            NOT NULL,
    email        VARCHAR(100)                            NOT NULL,
    password     VARCHAR(255)                            NOT NULL,
    enabled      BOOLEAN                                 NOT NULL,
    phone_number VARCHAR(20),
    first_name   VARCHAR(50),
    last_name    VARCHAR(80),


    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE orders
    ADD CONSTRAINT uc_orders_shipping_address UNIQUE (shipping_address_id);

ALTER TABLE roles
    ADD CONSTRAINT uc_roles_name UNIQUE (name);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE accessory
    ADD CONSTRAINT FK_ACCESSORY_ON_ID FOREIGN KEY (id) REFERENCES product (id);

ALTER TABLE addresses
    ADD CONSTRAINT FK_ADDRESSES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE cart_item
    ADD CONSTRAINT FK_CART_ITEM_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);

ALTER TABLE cart_item
    ADD CONSTRAINT FK_CART_ITEM_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE image
    ADD CONSTRAINT FK_IMAGE_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_SHIPPING_ADDRESS FOREIGN KEY (shipping_address_id) REFERENCES shipping_address (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE order_item
    ADD CONSTRAINT FK_ORDER_ITEM_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE order_item
    ADD CONSTRAINT FK_ORDER_ITEM_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);

ALTER TABLE rim
    ADD CONSTRAINT FK_RIM_ON_ID FOREIGN KEY (id) REFERENCES product (id);

ALTER TABLE tire
    ADD CONSTRAINT FK_TIRE_ON_ID FOREIGN KEY (id) REFERENCES product (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES users (id);