version: "3.8"
services:
  backend:
    build: ./TiresShopApp
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tire_shop
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=pass
    networks:
      - app-network
  frontend:
    build: ./TireShopFrontend
    ports:
      - "5174:80"
    depends_on:
      - backend
    networks:
      - app-network
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: tire_shop
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
volumes:
  postgres_data:

networks:
  app-network:
